spring:
  profiles:
    active: dev #默认为开发环境
  jmx:
    enabled: false
mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml

#pagehelper分页插件配置
pagehelper:
  # 数据库的方言
  helperDialect: mysql
  # 启用合理化，如果pageNum < 1 会查询第一页，如果pageNum > pages会查询最后一页
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
    root: info #日志配置DEBUG,INFO,WARN,ERROR
    com.zsl.traceapi: debug
#  file: demo_log.log #配置日志生成路径
#  path: /var/logs #配置日志文件名称
