server:
  port: 8088
spring:
  redis:
        host: 172.16.0.30 # Redis服务器地址
        database: 0 # Redis数据库索引（默认为0）
        port: 6379 # Redis服务器连接端口
        password: adminfeng5148@ # Redis服务器连接密码（默认为空）
        jedis:
          pool:
            max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
            max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
            max-idle: 8 # 连接池中的最大空闲连接
            min-idle: 0 # 连接池中的最小空闲连接
        timeout: 3000ms # 连接超时时间（毫秒）
  #rabbitmq
#  rabbitmq:
#    host: 193.112.186.190
#    port: 5672
#    virtual-host: /
#    username: dabing
#    password: dabing
#    publisher-confirms: true #如果对异步消息需要回调必须设置为true
#    listener:
#               simple:
#                 retry:
#                   enabled: true
#                   max-attempts: 5
#                   initial-interval: 2000
#                 default-requeue-rejected: false
  #kafka
  kafka:
     bootstrap-servers: 172.16.0.37:9092
     #生产者
     producer:
       retries: 0
       batch-size: 16384
       buffer-memory: 33554432
       key-serializer: org.apache.kafka.common.serialization.StringSerializer
       value-serializer: org.apache.kafka.common.serialization.StringSerializer
       properties:
         linger.ms: 1
     #消费者
     consumer:
       enable-auto-commit: false
       auto-commit-interval: 100ms
       key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
       value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
       properties:
         session.timeout.ms: 15000
       group-id: ckafka-0larvru5
  datasource:
    url: jdbc:mysql://172.16.0.8:2890/traceability_platform?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: zs-mall24
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  jackson:
    serialization:
      write-dates-as-timestamps: true
logging:
  path: /var/logs #配置日志生成路径
