spring:
  profiles:
    active: dev #默认为开发环境

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml

logging:
  level:
    root: info #日志配置DEBUG,INFO,WARN,ERROR
    com.zsl.traceapi: debug
#  file: demo_log.log #配置日志生成路径
#  path: /var/logs #配置日志文件名称
